apipublica:
    resource: "@ApipublicaBundle/Resources/config/routing.yml"
    prefix:   /public

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /public/doc
