XalokBundle\Entity\Image:
    type: entity
    table: image
    uniqueConstraints:
        UNIQ_C53D045F989D9B62:
            columns:
                - slug
        UNIQ_C53D045F953C1C61:
            columns:
                - source_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        slug:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 16000
            options:
                fixed: false
        sourceId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: source_id
        imageName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: image_name
        fields:
            type: json_array
            nullable: true
            length: null
            options:
                fixed: false
        credito:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        portalId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: portal_id
        imagePath:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: image_path
    manyToMany:
        gallery:
            targetEntity: Gallery
            cascade: {  }
            fetch: LAZY
            mappedBy: image
            inversedBy: null
            joinTable: null
            orderBy: null
        tag:
            targetEntity: Tag
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: image
            joinTable:
                name: image_tag
                joinColumns:
                    -
                        name: image_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: tag_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
