XalokBundle\Entity\LexikTranslationFile:
    type: entity
    table: lexik_translation_file
    uniqueConstraints:
        hash_idx:
            columns:
                - hash
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        domain:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        locale:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        extention:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        path:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        hash:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
