xalok:
    resource: "@XalokBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /api

api:
    resource: "@BackendBundle/Resources/config/routing_api.yml"
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
