# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    clave_secreta : "3l_financi3ro_rediseni0"
    token_ttl: 7776000 # 60*60*24*30*3
    folderLog: /

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
     listener500:
        class: BackendBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
     app.jwt_auth:
         class: AppBundle\Services\JwtAuth
         arguments: ["@doctrine.orm.entity_manager","@security.encoder_factory", "%clave_secreta%", "%token_ttl%"]

     app.helpers:
         class: AppBundle\Services\Helpers
         arguments: ["@app.jwt_auth","%kernel.root_dir%", "@service_container","@doctrine.orm.entity_manager","@request_stack"]

     app.token_authenticator:
         class: AppBundle\Security\TokenAuthenticator
         arguments: ["@app.helpers"]

     app.config_provider:
        class: AppBundle\Services\ConfigProvider
        arguments:
            - "%kernel.root_dir%"
     app.users:
        class: AppBundle\Services\Users
        arguments: ["@service_container","@security.authorization_checker","@security.token_storage","@doctrine.orm.entity_manager"]

     app.search:
        class: AppBundle\Services\Search
        arguments: ["@app.helpers","@fos_elastica.index_manager"]

     listener.access_denied.handler:
        class: AppBundle\Security\MyAccessDeniedHandler

     app.pages_clone:
        class: AppBundle\Services\PageClone
        arguments: ["@app.helpers","@security.token_storage","@doctrine.orm.entity_manager"]

     elastica.sync.foselasctica:
        class: BackendBundle\EventListener\CustomElasticaListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postUpdate, connection: default }
