<?php

namespace BackendBundle\Repository;

/**
 * PortadaFoldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortadaFoldsRepository extends \Doctrine\ORM\EntityRepository
{
}
