<?php

namespace BackendBundle\Repository;

/**
 * TopNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
