<?php

namespace BackendBundle\Repository;

/**
 * UserVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
