BackendBundle\Entity\Category:
    type: entity
    table: category
    indexes:
        type_idx:
            columns:
                - type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        parentId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: parent_id
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
#        image:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#            column: image
        template:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        articleTemplate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: article_template
        lft:
            type: integer
            nullable: false
            options:
                unsigned: false
        rgt:
            type: integer
            nullable: false
            options:
                unsigned: false
        root:
            type: integer
            nullable: true
            options:
                unsigned: false
        lvl:
            type: integer
            nullable: false
            options:
                unsigned: false
        slug:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        type:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
        radar:
            type: boolean
            nullable: true
        portalId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: portal_id
        color:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        svg:
            type: string
            nullable: true
            length: 4294967295
            options:
                fixed: false
        slug_redirect:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
    manyToOne:
        image:
            targetEntity: Image
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                image:
                    referencedColumnName: id
                    onDelete: cascade
            orphanRemoval: false
        wallpaper:
            targetEntity: Image
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                walpaper_id:
                    referencedColumnName: id
                    onDelete: cascade
            orphanRemoval: false
    lifecycleCallbacks: {  }
