BackendBundle\Entity\EeCandidato:
    type: entity
    table: ee_candidato
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        candidato:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
        foto:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estatus:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
