BackendBundle\Entity\File:
    type: entity
    table: file
    uniqueConstraints:
        UNIQ_8C9F3610989D9B62:
            columns:
                - slug
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        slug:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 16000
            options:
                fixed: false
        filename:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        filesize:
            type: integer
            nullable: false
            options:
                unsigned: false
        mimeType:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: mime_type
    manyToMany:
        tag:
            targetEntity: Tag
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: file
            joinTable:
                name: file_tag
                joinColumns:
                    -
                        name: file_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: tag_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
