BackendBundle\Entity\Layout:
    type: entity
    table: layout
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        html:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        stylesheets:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        javascripts:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
