BackendBundle\Entity\Personaje:
    type: entity
    table: personaje
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
        titulo:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
        puesto:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
            column: Puesto
        foto:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
