BackendBundle\Entity\Portal:
    type: entity
    table: portal
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Portal identifier'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                comment: 'Portal name'
        domain:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
                comment: 'Prime domain of the portal'
    lifecycleCallbacks: {  }
