BackendBundle\Entity\StaticPage:
    type: entity
    table: static_page
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        slug:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
                default: ''
        title:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
                default: ''
        text:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
