BackendBundle\Entity\WfGroup:
    type: entity
    table: wf_group
    uniqueConstraints:
        UNIQ_7DEB37C55E237E06:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        roles:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
    manyToMany:
        user:
            targetEntity: WfUser
            cascade: {  }
            fetch: LAZY
            mappedBy: group
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
